
spring.datasource.url=jdbc:postgresql://localhost:5432/collections
spring.datasource.username=collections_admin
spring.datasource.password=super_secret_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
